In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from matplotlib import style
from sklearn.preprocessing import StandardScaler
import seaborn as sb
import warnings

In [42]:
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("Assets/homeprices (1).csv")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
average_value= df['bedrooms'].mean()
average_value

4.2

In [11]:
df.fillna(4.0, inplace = True) #filled average value in NaN. Cannot remove because data is very small.

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
numerical = ["area","bedrooms","age"]

In [15]:
ss = StandardScaler()

In [16]:
X = ss.fit_transform(df[numerical])

In [17]:
X

array([[-1.52162173, -1.09321633,  0.46257302],
       [-0.77633762, -0.15617376, -0.19824558],
       [-0.40369556, -0.15617376,  0.19824558],
       [ 0.34158855, -1.09321633,  1.78421022],
       [ 1.08687266,  0.78086881, -1.12339162],
       [ 1.27319369,  1.71791138, -1.12339162]])

In [18]:
X.shape

(6, 3)

In [19]:
y = df.iloc[:,-1]

In [20]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [21]:
y.shape

(6,)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [23]:
lr = LinearRegression()

In [24]:
lr.fit(X_train, y_train)

LinearRegression()

In [25]:
lr.coef_

array([ 126797.28223132, -186891.18868007, -144706.88315091])

In [26]:
lr.intercept_

605562.5

In [28]:
pred= lr.predict(X_test)

In [29]:
r2_score(y_test, pred) #Model is underfit due to very less data

-1.1820507812499947

## Let's train model again on whole data

In [30]:
lr.fit(X,y) #trained model with whole data

LinearRegression()

In [31]:
pred= lr.predict(X_test)

In [32]:
r2_score(y_test, pred) 

0.9877260519206261

In [33]:
#Let's try it on unseen data and check accuracy

In [39]:
predict = pd.read_csv("Assets/predict_home.csv")
predict

area  bedrooms  age
0  3979         5   13
1  3609         2    5
2  4974         5   34
3  3214         3   37
4  3330         5   37
5  3609         2    5
6  3331         5    3
7  3350         3    7
8  4974         5   30

In [64]:
pred = lr.predict(predict)
pred

array([2.39771482e+08, 2.17638638e+08, 2.99102075e+08, 1.93123919e+08,
       2.00150638e+08, 2.17638638e+08, 2.01042164e+08, 2.02037185e+08,
       2.99199884e+08])

In [57]:
print("Predictions on Unseen Data:")
print("Mean prediction:", round(pred.mean()))
print("Min prediction:", round(pred.min()))
print("Max prediction:", round(pred.max()))

Predictions on Unseen Data:
Mean prediction: 229967180
Min prediction: 193123919
Max prediction: 299199884
