In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from matplotlib import style
from sklearn.preprocessing import StandardScaler
import seaborn as sb
import warnings
from word2number import w2n 

In [23]:
df = pd.read_csv('Assets/hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [24]:
df.shape

(8, 4)

# Need to clean this data first

In [25]:
#Lets convert data of experience in numerical form using a liberary called word2number:

In [5]:
pip install word2number

Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5590 sha256=a262a8a225dcad847c597df8a0a8374b01ef673627587cb175f017b43a435216
  Stored in directory: c:\users\shtlp_0060\appdata\local\pip\cache\wheels\5b\79\fb\d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [26]:
df['experience'] 

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [27]:
df['experience'] = df['experience'].apply(lambda x:w2n.word_to_num(x) if isinstance(x,str) else x) 

In [28]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [29]:
df.shape

(8, 4)

In [31]:
df['experience'].mean()

6.333333333333333

In [37]:
df.loc[[1],'experience'] = df.loc[[1],'experience']=5
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         5.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [38]:
df.loc[[0],'experience'] = df.loc[[0],'experience'].fillna(4)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         4.0                    8.0                           9      50000
1         5.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [41]:
df.loc[[6],'test_score(out of 10)'] = df.loc[[6],'test_score(out of 10)'].fillna(7)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0         4.0                    8.0                           9      50000   
1         5.0                    8.0                           6      45000   
2         5.0                    6.0                           7      60000   
3         2.0                   10.0                          10      65000   
4         7.0                    9.0                           6      70000   
5         3.0                    7.0                          10      62000   
6        10.0                    7.0                           7      72000   
7        11.0                    7.0                           8      80000   

   test_score(out of 10)\t  
0                      NaN  
1                      NaN  
2                      NaN  
3                      NaN  
4                      NaN  
5                      NaN  
6                      7.0  
7                      NaN

In [46]:
df.drop('test_score(out of 10)\t',axis = 1, inplace = True)

In [47]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         4.0                    8.0                           9      50000
1         5.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

# Finally we have clean data

In [48]:
#Now let's scale the data and split it

In [49]:
X = df.iloc[:,:-1]

In [50]:
X

experience  test_score(out of 10)  interview_score(out of 10)
0         4.0                    8.0                           9
1         5.0                    8.0                           6
2         5.0                    6.0                           7
3         2.0                   10.0                          10
4         7.0                    9.0                           6
5         3.0                    7.0                          10
6        10.0                    7.0                           7
7        11.0                    7.0                           8

In [51]:
ss = StandardScaler()

In [52]:
X = ss.fit_transform(X)

In [54]:
X

array([[-0.62123652,  0.20851441,  0.73240961],
       [-0.28991038,  0.20851441, -1.22068269],
       [-0.28991038, -1.4596009 , -0.56965192],
       [-1.28388882,  1.87662973,  1.38344038],
       [ 0.37274191,  1.04257207, -1.22068269],
       [-0.95256267, -0.62554324,  1.38344038],
       [ 1.36672035, -0.62554324, -0.56965192],
       [ 1.6980465 , -0.62554324,  0.08137885]])

In [53]:
X.shape

(8, 3)

In [55]:
y = df.iloc[:,-1]

In [56]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [57]:
y.shape

(8,)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 0)

In [59]:
lr = LinearRegression()

In [60]:
lr.fit(X_train, y_train)

LinearRegression()

In [62]:
lr.coef_  #three coef means multi-linear regression is applied automatically

array([13936.31390789,  6194.90705355,  7634.10418034])

In [63]:
lr.intercept_

60898.65391383038

In [65]:
pred = lr.predict(X_test)


In [72]:
pred

array([71721.73344729, 43467.49786336])

In [66]:
r2_score(y_test, pred) #due to less data model is underfit

-2.797236932951675

In [ ]:
#Let's train the model on full data

In [67]:
lr.fit(X,y)

LinearRegression()

In [69]:
lr.coef_

array([10804.85203114,  2330.06341951,  5543.67274139])

In [70]:
lr.intercept_

63000.0

In [73]:
pred = lr.predict(X_test)

In [74]:
pred

array([73151.69194866, 53308.63477246])

In [75]:
r2_score(y_test, pred) #Due to less data model is showing very less accuracy

0.3597116256540632

In [76]:
y_test

6    72000
2    60000
Name: salary($), dtype: int64

In [77]:
pred

array([73151.69194866, 53308.63477246])