In [2]:
# How to convert 1d to 2d

In [ ]:
import numpy as np

In [4]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x.shape

(10,)

In [8]:
x.ndim

1

In [10]:
x_new = x.reshape(10,1) #row,column

In [12]:
x_new #converted to 2D

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
x_new.shape

(10, 1)

In [16]:
x_new.ndim

2

In [18]:
x_new = x.reshape(-1,1) #same work last element and 1

In [20]:
x_new

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
x_new.shape

(10, 1)

In [24]:
x_new.ndim

2